### ISSUE TITLE
boutdata breaks BOUT++ v4.4.1

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/boutdata#59]
1906985c23eeaf3ef09222ddb8d88854675bdabb is breaking BOUT v4.4.1

The error is:
```
Making restart I/O test
Grid sizes:  8 16 4
Traceback (most recent call last):
  File "/builddir/build/BUILD/BOUT++-v4.4.1/build_mpich/tests/integrated/test-restart-io/./runtest", line 90, in <module>
    restart.redistribute(nproc, path=restartdir, output='data')
  File "/builddir/boutdata/boutdata/restart.py", line 641, in redistribute
    jyseps2_1 = f["jyseps2_1"]
  File "/usr/lib/python3.10/site-packages/boututils/datafile.py", line 319, in __getitem__
    return self.impl.__getitem__(name)
  File "/usr/lib/python3.10/site-packages/boututils/datafile.py", line 437, in __getitem__
    raise KeyError("No variable found: " + name)
KeyError: 'No variable found: jyseps2_1'
```

Reverting 1906985c23eeaf3ef09222ddb8d88854675bdabb fixes the issue.

**Comment by johnomotani** [comment]
Better not to revert a bug-fix! I'll add a work-around for files that are missing `jyseps2_1`...

**Comment by dschwoerer** [comment]
If the regression is worse then the old bug, and I don't have time for a proper fix, then reverting is the right solution. But #62 is of course much better :-)
